Add skeleton of the project
cmolinan/Portfolio-project pull request #1
Opened 2022-07-01 03:28 UTC by cmolinan

### Added Changes
- Add the toolbar section 
- Add the header section 
- Add a .gitignore file
- Set up the linter for HTML and CSS
- Add descriptive README

2022-07-01 04:29 UTC, aboongm requested changes
Hi @cmolinan , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![request_changes_1](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

## Highlights
- All linters are passing ✔️
- Good commit history ✔️
- Good PR description ✔️

## Required Changes ♻️

_Please check the comments below for the required changes._

## Optional suggestions

[OPTIONAL] Please update the README. Check comments below

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-01 04:29 UTC, aboongm commented on index.html
> +                <img src="images/union.svg" alt="menu" />
- The logo should have a tag link. This is going to become your logo, so plan it in such a way.
- The hamburger menu should be inside a nav tag

2022-07-01 04:29 UTC, aboongm commented on styles.css
> +}
- toolbar class for the header section should use flexbox. Using the flex will help you in controlling the items viz the logo and the navigation items which you are yet to put.

2022-07-01 04:29 UTC, aboongm commented on styles.css
> +  background-repeat: no-repeat;
- You have applied the background-image in the container class on the main section. This should be preferably applied to the headline class. It depends on how you want to structure your future code viz portfolio section, about-me section, and contact me section. If you intend to put those sections inside the main tag with the container class, you will have a problem.

2022-07-01 04:29 UTC, aboongm commented on index.html
> +            <p>I’m a software developer! I can help you<br>build a product , feature or website Look<br>through some of my work and<br>experience! If you like what you see and<br>have a project you n
- Your h2 tag with your main title should be an h1 tag

2022-07-01 04:29 UTC, aboongm commented on index.html
> +              </div>
- Your list of icons should use a ul tag to group them, and li tag per icon. Each icon should have a link (a tag)

2022-07-01 04:29 UTC, aboongm commented on styles.css
> +}
- Your headline class inside headline section should use flexbox to be able to control the contents inside.
- Follow the figma design for fonts, font-size, and color. The margin/padding should feel similar to the figma design.

2022-07-01 04:29 UTC, aboongm commented on index.html
> +        <header>
![port-1](https://user-images.githubusercontent.com/49184579/176822859-d4302d60-58ab-4c20-8742-de490e67632a.png)

Please compare your design and the figma and see the difference.
1. There is a margin around your content. Try if applying margin of 0 to body remove the space
2. You have set the width to 375px in container class and this is preventing your website from being responsive. You have to set the max-width to 100% or vw
3. The background image is not the same as in figma design
4. The font of your main title is not the same as in the figma design.  Everywhere its imperative that you follow the figma design for fonts, font-size, and color. The margin/padding should feel similar to the figma design.

2022-07-01 06:31 UTC, aboongm commented on README.md
> -
@cmolinan The README update is optional. You can do it at the last. The other required changes should be implemented as they are part of the project requirements. Please let me know where you are having problems.

2022-07-02 03:41 UTC, Ismailco approved these changes
### Hi @cmolinan,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![cr-approve](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)


## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-02 04:24 UTC, merged