Adding files for mobile version
cmolinan/Portfolio-project pull request #2
Opened 2022-07-02 21:27 UTC by cmolinan

### Added Changes for mobile version
Add "works" section
Add "about" section 
Update of README files

2022-07-02 22:30 UTC, tufoinnkuo10 requested changes
Hi @cmolinan 

Great job so far. There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅figma design followed

## Required Changes ♻️♻️
Check the comments under the review

![tufoin](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

Optional suggestions
- [ optional ] please next time do not open a new pull request unless the old one has already been approved by a code reviewer.
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-07-02 22:30 UTC, tufoinnkuo10 commented on index.html
> +        <section class="work-section">
- [ ] kindly maintain the white background in the work section as in the figma version

2022-07-02 22:30 UTC, tufoinnkuo10 commented on README.md
>  ## Authors
- [ ] kindly add the authors name and other necessary links

2022-07-02 22:30 UTC, tufoinnkuo10 commented on README.md
>  ![](https://img.shields.io/badge/Microverse-blueviolet)
- [ ] please add a brief description of what you did in the project

2022-07-03 00:28 UTC, vickymarz approved these changes
Hi @cmolinan , 

# 🟢  Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
congratulations!  🎉💯🌟 

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- The README is well documented ✅ 
- Linters are working properly ✅ 
<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-03 00:35 UTC, merged